#ifdef FRAMESTORE
#define MEMORY_MAX_LINES FRAMESTORE
#else
#define MEMORY_MAX_LINES 1000
#endif

#ifdef VARMEMSIZE
#define MEM_SIZE VARMEMSIZE
#else
#define MEM_SIZE 1000
#endif

#define MAX_USER_INPUT 1000
#define CMD_MAX_CHARS 100
#define SCRIPT_MAX_LINES 150
#define FRAME_SIZE 3
#define PAGE_SIZE FRAME_SIZE
#define N_FRAMES (MEMORY_MAX_LINES / FRAME_SIZE)
#define PAGE_TBL_SIZE (SCRIPT_MAX_LINES / PAGE_SIZE) + 1
